name: esptool
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0-24.0.dev
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  libusb_new: ^1.0.0
  ffi: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        # package: com.example.esptool
        pluginClass: EsptoolPlugin
        dartPluginClass: TransportAndroid
      ios:
        pluginClass: EsptoolPlugin
      linux:
        pluginClass: EsptoolPlugin
        dartPluginClass: TransportLinux
      macos:
        pluginClass: EsptoolPlugin
      windows:
        pluginClass: EsptoolPluginCApi
        dartPluginClass: TransportWindows
      web:
        pluginClass: EsptoolWeb
        fileName: esptool_web.dart

